virtual-ease:
  # 名称
  name: virtual-ease
  # 版本
  version: ${revision}
  # 版权年份
  copyrightYear: 2024

server:
  port: 8130
spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  profiles:
    active: dev

springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  #  swagger-ui:
  #    # 持久化认证数据
  #    persistAuthorization: true
  info:
    # 标题
    title: '标题：${ruoyi.name}多租户管理系统_接口文档'
    # 描述
    description: '描述：用于管理集团旗下公司的人员信息,具体包括XXX,XXX模块...'
    # 版本
    version: '版本号: ${ruoyi.version}'
    # 作者信息
    contact:
      name: 突突兔
      email: 1473601995@qq.com
      url: https://gitee.com/AwakeSleeper/virtual-ease
  components:
    # 鉴权方式配置
    security-schemes:
      apiKey:
        type: APIKEY
        in: HEADER
        name: ${sa-token.token-name}
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
#    - group: 1.演示模块
#      packages-to-scan: org.dromara.demo
#    - group: 2.通用模块
#      packages-to-scan: org.dromara.web
#    - group: 3.系统模块
#      packages-to-scan: org.dromara.system
#    - group: 4.代码生成模块
#      packages-to-scan: org.dromara.generator